name: build + publish

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Create .env
        run: |
          touch .env
          echo PUBLIC_SUPABASE_URL=${{ secrets.PUBLIC_SUPABASE_URL }} >> .env
          echo PUBLIC_SUPABASE_ANON_KEY=${{ secrets.PUBLIC_SUPABASE_ANON_KEY }} >> .env

      - name: Publish Docker Image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ github.token }}
          containerRegistry: true
          
      # - name: Login to Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #         registry: ghcr.io
      #         username: ${{ github.repository_owner }}
      #         password: ${{ secrets.GH_TOKEN }}
    
      # - name: Preset Image Name
      #   run: echo "IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    
      # - name: Build and push Docker Image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ env.IMAGE_URL }}

      - name: Deploy on CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: https://caprover.faststakdev.com
          app: 'faststack-sveltekit'
          token: '${{ secrets.APP_TOKEN }}'
          image: 'ghcr.io/cloud303-epahk/test:latest'